### ISSUE TITLE
Script never finds any additions

### ISSUE THREAD

**Issue by Fireraiser** [sup3rmark/PlexCheck#2]
$response = Invoke-WebRequest "$url`:$port/library/recentlyAdded/?X-Plex-Token=$Token" -Headers @{"accept"="application/json"}

$jsonlibrary = ConvertFrom-JSON $response.Content

Write-Output "JsonLIb :" $jsonlibrary
Write-Output "Children :" $jsonlibrary._children

# Grab those libraries!
$movies = $jsonLibrary._children |
Where-Object {$_.type -eq 'movie' -AND $_.addedAt -gt (Get-Date (Get-Date).AddDays(-$days) -UFormat "%s")} |
Select-Object * |
Sort-Object addedAt

$tvShows = $jsonLibrary._children |
Where-Object {$_.type -eq 'season' -AND $_.addedAt -gt (Get-Date (Get-Date).AddDays(-$days) -UFormat "%s")} |
Group-Object parentTitle

The Write-Outputs show that $jsonlibrary is populated but that $jsonlibrary._children is empty. What am I doing wrong?

**Comment by sup3rmark** [comment]
Nothing on your end! Plex changed the response thrown by the API and I
haven't had time to update the script yet (just figured it out the other
day). Hope to have it up soon, sorry about that.

**Comment by Fireraiser** [comment]
Thank you. It was driving me crazy.  I'm new to both PowerShell and Plex.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Dec 20, 2016 at 10:55 PM +0000, "sup3rmark" <notifications@github.com<mailto:notifications@github.com>> wrote:

Nothing on your end! Plex changed the response thrown by the API and I
haven't had time to update the script yet (just figured it out the other
day). Hope to have it up soon, sorry about that.

**Comment by sup3rmark** [comment]
Hey,
I've updated the script to work with the changes to the Plex API. Check it
out on GitHub and let me know if it still gives you problems!

-Mark

**Comment by Fireraiser** [comment]
Thanks Mark. This works now, but with a glitch. I have the BBC TV Series "Class". Plex correctly identifies it as http://thetvdb.com/?tab=series&id=309893&lid=7 but the script gets the info from http://www.imdb.com/title/tt0085346/. Can the script get the metadata from Plex itself?

**Comment by sup3rmark** [comment]
I don't pull metadata from Plex because of the posters, actually. Plex
stores the images locally, and references the files in the metadata. I'd
have to embed the images in each email, which would cause the messages'
filesize to be too large.

Unfortunately, the response the Plex API gives for TV shows is a lot more
vague than what it spits back for movies, which is why it's having trouble
finding the right thing: TV shows don't include a year, so I can't include
that in the search, which makes it inherently more vague. Here's what I'm
working with for TV shows:


​
As you can see, not much there to let me narrow it down.

I'll poke around a bit more and see if I can't dive any deeper into the
library for shows and get more data, but it'll probably take a few days.
